### ISSUE TITLE
full-ad ban ip from renew letsencrypt certificat

### ISSUE THREAD

**Issue by PHB-fra** [romainmarcoux/malicious-ip#2]
hi Romain, 

Thank you for your work it's amazing !
with full-ad on my router, i can't renew cerbot certificat (via http method) 

Could you whitelist let's encrypt ip ? 
maybe this url help you : https://forum.opnsense.org/index.php?topic=16108.0

best regard.

**Comment by romainmarcoux** [comment]
Hello,
Thanks for the report.
The link provided is outdated. Let's Encrypt no longer provides the IP addresses used for security reasons.
https://letsencrypt.org/docs/faq/#what-ip-addresses-does-let-s-encrypt-use-to-validate-my-web-server
I modified the statistical analysis algorithm to remove Let's Encrypt IPs.
The problem is solved.
